on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:

jobs:
  lint:
    runs-on: ubuntu-20.04

    container:
      image: node:10

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install tslint
        run: npm install tslint

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-20.04

    container:
      image: node:10

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-20.04

    container:
      image: node:10

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dev packages
        run: npm install --dev

      - name: Test
        run: npm run build-test